# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
latex: false
fortran: true
warnings_are_errors: false

r_packages:
  - abind
  - deldir
  
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgsl0-dev 
      - bwidget
      - gcc

before_install:
  - mkdir ~/.R
  - echo -e "CXXFLAGS = -Ofast -march=native -fpic -pipe -std=c++11\nMAKE = make -j8" > ~/.R/Makevars

after_success:
  - Rscript -e 'covr::codecov(branch = "develop")'

notifications:
  email:
  on_success: change
on_failure: change
